// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';
import {session} from '../models';

export function ClearFrames():Promise<void>;

export function GenerateGIF(arg1:core.GifOptions):Promise<main.GenerateResult>;

export function GetFrames():Promise<Array<session.FrameItem>>;

export function RemoveFrame(arg1:string):Promise<Array<session.FrameItem>>;

export function ReorderFrames(arg1:Array<string>):Promise<Array<session.FrameItem>>;

export function ScanClipboard():Promise<session.AddResult>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;
