// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearFrames() {
  return window['go']['main']['App']['ClearFrames']();
}

export function GenerateGIF(arg1) {
  return window['go']['main']['App']['GenerateGIF'](arg1);
}

export function GetFrames() {
  return window['go']['main']['App']['GetFrames']();
}

export function RemoveFrame(arg1) {
  return window['go']['main']['App']['RemoveFrame'](arg1);
}

export function ReorderFrames(arg1) {
  return window['go']['main']['App']['ReorderFrames'](arg1);
}

export function ScanClipboard() {
  return window['go']['main']['App']['ScanClipboard']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}
